/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MortalitiesRouteImport } from './routes/mortalities'
import { Route as IndexRouteImport } from './routes/index'

const MortalitiesRoute = MortalitiesRouteImport.update({
  id: '/mortalities',
  path: '/mortalities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mortalities': typeof MortalitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mortalities': typeof MortalitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mortalities': typeof MortalitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mortalities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mortalities'
  id: '__root__' | '/' | '/mortalities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MortalitiesRoute: typeof MortalitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mortalities': {
      id: '/mortalities'
      path: '/mortalities'
      fullPath: '/mortalities'
      preLoaderRoute: typeof MortalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MortalitiesRoute: MortalitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
